<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'5Yas6L+Q5paw6Ze7');
$cfg_Cs[2]=array(0,1,1,'57uE57uH5py65p6E');
$cfg_Cs[3]=array(0,1,1,'5Zy65Zyw56255bu6');
$cfg_Cs[4]=array(0,1,1,'5Lqu5Li95YaF6JKZ5Y+k');
$cfg_Cs[5]=array(0,1,1,'5Yas6L+Q55m+56eR');
$cfg_Cs[6]=array(0,1,1,'5Yas6L+Q5ZCI5L2c');
$cfg_Cs[7]=array(1,1,1,'5a6Y5pa55Y+R5biD');
$cfg_Cs[8]=array(1,1,1,'6IGa54Sm');
$cfg_Cs[9]=array(1,1,1,'6LWb5LqL');
$cfg_Cs[10]=array(0,1,1,'5q+U6LWb6aG555uu');
$cfg_Cs[11]=array(0,1,1,'57K+5b2p5Zue6aG+');
$cfg_Cs[12]=array(11,1,1,'57K+5b2p5Zu+6ZuG');
$cfg_Cs[13]=array(11,1,1,'6KeG6aKR6ZuG6ZSm');
?>